INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Звезда', 1, 7.20, true, 1, 1, 'Старейшее в стране, единственное ежедневное издание на белорусском языке. Новости политической,
экономической, хозяйственной и культурной жизни');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Коммерсантъ', 2, 13.50, true, 1, 1, 'Ежедневная российская деловая газета. Достоверно, оперативно и объективно о событиях в бизнесе, политике и обществе');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Аргументы и Факты в Беларуси', 3, 7.50, true, 3, 1, 'Вся информация в одной газете: независимо, взвешенно, объективно. Актуальные интервью, комментарии, эксклюзивные подробности из коридоров власти. Важно каждому: пенсии, налоги, деньги. Глас народа.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('FORBES/ФОРБС', 4, 24.00, true, 6, 2, 'Журнал Forbes — один из самых популярных журналов о бизнесе. На страницах Forbes публикуются истории успехов и провалов, рассказы о самых громких проектах, истории жизни известных предпринимателей, новые идеи для бизнеса и инвестиций, журналистские расследования, ежегодные авторитетные рейтинги, раскрываются причины и следствия наиболее значительных событий и т.д.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('РБК', 5, 20.50, true, 1, 1, 'Целостная картина дня и анализ ключевых событий, влияющих на принятие решений. Каждое утро по рабочим дням.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Журнал РБК', 5, 12.00, true, 6, 2, 'Самые актуальные тренды в мировой и российской экономике. Новые возможности и ниши для бизнеса.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Harvard Business Review - Россия', 6, 32.00, true, 6, 2, 'Журнал «Harvard Business Review - Россия» считается одним из самых авторитетных изданий по менеджменту в мире. С журналом сотрудничают 480 российских топ-менеджеров и предпринимателей, в каждом номере они делятся с читателями своим опытом.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Белорусы и рынок', 7, 4.54, true, 3, 1, 'Аналитический еженедельник для деловых людей. Рассказывает о важнейших событиях в экономике,
предоставляет объективную деловую информацию, необходимую для принятия решений в ведении
бизнеса.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Прессбол', 8, 27.54, true, 2, 1, 'Публикации по спортивной тематике');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Бюллетень Министерства труда и социальной защиты Республики Беларусь', 9, 17.95, true, 6, 3, 'Официальное издание Министерства труда и социальной защиты: оперативные комментарии к
законодательным актам, советы специалистов-практиков.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Вожык', 1, 4.75, true, 6, 2, 'Республиканский цветной литературно- художественный журнал сатиры и юмора. Публикует фельетоны,
стихи, юморески, пародии, басни, эпиграммы, карикатуры. Издается на белорусском языке.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Экономический бюллетень НИЭИ Министерства экономики Республики Беларусь', 10, 18.14, true, 6, 3, 'Макроэкономика: теория и методология; планирование и прогнозирование; анализ социально -
экономического развития; перспективы развития экономики Беларуси.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('БелГазета', 11, 8.85, true, 3, 1, 'Информационно - аналитический еженедельник.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Спортивная панорама', 12, 19.77, true, 1, 1, 'Специализированное издание, которое оперативно знакомит общество с новостями мирового и
национального спорта.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Теленеделя', 13, 2.27, true, 3, 1, 'Газета с телепрограммой на неделю вперѐд, более 60 каналов телевидения. Новости кино,
телевидения, музыки.');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('COSMOPOLITAN РУССКОЕ ИЗДАНИЕ', 14, 5.86, true, 3, 2, ' «Девушка в стиле Cosmo» молода, независима и энергична. Она сама выбирает свой путь и пытается
стать лучше, красивее, а главное - счастливее, в чем ей помогает ее любимый журнал');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('ESQUIRE (ЭСКВАЙР)', 14, 5.81, true, 3, 2, 'Журнал для успешных мужчин');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('HELLO! (ХЭЛЛОУ!)', 15, 10.26, true, 2, 2, 'Знаменитый журнал о знаменитых людях. Частная жизнь звезд, интервью, репортажи');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('NATIONAL GEOGRAPHIC РОССИЯ (НЭШИОНАЛ ДЖИОГРЭФИК РОССИЯ)', 16, 6.53, true, 6, 2, 'Журнал отличают высочайшего уровня профессиональная фотожурналистика и эксклюзивная информация о
крупнейших и наиболее значимых открытиях, достижениях и исследованиях в области естествознания,
географии, истории, археологии');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('NATIONAL GEOGRAPHIC TRAVELER (НЭШИОНАЛ ДЖИОГРЭФИК ТРЕВЕЛЕР)', 16, 5.97, true, 6, 2, 'В журнале собраны лучшие экспертные мнения и вся практическая информация, которая может
понадобиться при планировании поездок. Исключительные фотографии способны передать колорит
местной жизни');
INSERT INTO periodicals.periodicals (name, publisher_id, month_price, periodical_availablity, frequencies_id, periodicals_categories_id, periodical_description) VALUES ('Вокруг света', 17, 5.94, true, 6, 2, 'Один из самых популярных российских журналов, публикующий материалы о путешествиях, загадках истории,
новых научных открытиях и технических достижениях, а также рассказы о знаменитых людях');