INSERT INTO periodicals.publishers (publisher_name) VALUES ('АО "АС РУС МЕДИА"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('АО "Бизнес Ньюс Медиа"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('АО "Коммерсантъ"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('АО "РОСБИЗНЕСКОНСАЛТИНГ"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ЗАО "Медиарынок"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('Издательский дом "Звезда"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ООО "Аргументы и факты в Белорусси"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ООО "БЕЛГАЗЕТА"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ООО "Газета "Теленеделя"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ООО "Прессбол-91"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ООО "Форвард Медиа Групп"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ООО "Фэшн Пресс"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ООО "Хёрст Шкулёв Паблишинг"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('ООО "Ясно Паблишинг"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('Редакция газеты "Спортивная панорама"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('Учреждение "Научно-исследовательский институт труда Министерства труда и социальной защиты Республики Беларусь"');
INSERT INTO periodicals.publishers (publisher_name) VALUES ('Учреждение "Научно-исследовательский экономический институт Министерства экономики Республики Беларусь"');